# Generated by Django 3.1.3 on 2021-01-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
